import { BiomeId } from './biomes';

export const BIOME_COLORS = new Map<number, [number, number, number]>([
  [BiomeId.ocean,                [0, 0, 112]],
  [BiomeId.plains,               [141, 179, 96]],
  [BiomeId.desert,               [250, 148, 24]],
  [BiomeId.windswept_hills,      [96, 96, 96]],
  [BiomeId.forest,               [5, 102, 33]],
  [BiomeId.taiga,                [11, 102, 89]],
  [BiomeId.swamp,                [7, 249, 178]],
  [BiomeId.river,                [0, 0, 255]],
  [BiomeId.nether_wastes,        [87, 37, 38]],
  [BiomeId.the_end,              [128, 128, 255]],
  [BiomeId.frozen_ocean,         [112, 112, 214]],
  [BiomeId.frozen_river,         [160, 160, 255]],
  [BiomeId.snowy_plains,         [255, 255, 255]],
  [BiomeId.mushroom_fields,      [255, 0, 255]],
  [BiomeId.beach,                [250, 222, 85]],
  [BiomeId.jungle,               [83, 123, 9]],
  [BiomeId.sparse_jungle,        [98, 139, 23]],
  [BiomeId.deep_ocean,           [0, 0, 48]],
  [BiomeId.stony_shore,          [162, 162, 132]],
  [BiomeId.snowy_beach,          [250, 240, 192]],
  [BiomeId.birch_forest,         [48, 116, 68]],
  [BiomeId.dark_forest,          [64, 81, 26]],
  [BiomeId.snowy_taiga,          [49, 85, 74]],
  [BiomeId.old_growth_pine_taiga,[89, 102, 81]],
  [BiomeId.windswept_forest,     [80, 112, 80]],
  [BiomeId.savanna,              [189, 178, 95]],
  [BiomeId.savanna_plateau,      [167, 157, 100]],
  [BiomeId.badlands,             [217, 69, 21]],
  [BiomeId.wooded_badlands,      [176, 151, 101]],
  [BiomeId.warm_ocean,           [0, 0, 172]],
  [BiomeId.lukewarm_ocean,       [0, 0, 144]],
  [BiomeId.cold_ocean,           [32, 32, 112]],
  [BiomeId.deep_warm_ocean,      [0, 0, 80]],
  [BiomeId.deep_lukewarm_ocean,  [0, 0, 64]],
  [BiomeId.deep_cold_ocean,      [32, 32, 56]],
  [BiomeId.deep_frozen_ocean,    [64, 64, 144]],
  [BiomeId.sunflower_plains,     [181, 219, 136]],
  [BiomeId.flower_forest,        [45, 142, 73]],
  [BiomeId.ice_spikes,           [180, 220, 220]],
  [BiomeId.old_growth_birch_forest,[88, 156, 108]],
  [BiomeId.old_growth_spruce_taiga,[129, 142, 121]],
  [BiomeId.windswept_savanna,    [229, 218, 135]],
  [BiomeId.eroded_badlands,      [255, 109, 61]],
  [BiomeId.bamboo_jungle,        [118, 142, 20]],
  [BiomeId.soul_sand_valley,     [94, 56, 48]],
  [BiomeId.crimson_forest,       [221, 8, 8]],
  [BiomeId.warped_forest,        [73, 144, 123]],
  [BiomeId.basalt_deltas,        [104, 95, 104]],
  [BiomeId.dripstone_caves,      [149, 127, 104]],
  [BiomeId.lush_caves,           [56, 118, 29]],
  [BiomeId.deep_dark,            [10, 30, 30]],
  [BiomeId.meadow,               [130, 185, 120]],
  [BiomeId.grove,                [74, 97, 73]],
  [BiomeId.snowy_slopes,         [196, 210, 218]],
  [BiomeId.frozen_peaks,         [165, 195, 210]],
  [BiomeId.jagged_peaks,         [192, 202, 199]],
  [BiomeId.stony_peaks,          [123, 143, 116]],
  [BiomeId.cherry_grove,         [228, 160, 191]],
  [BiomeId.mangrove_swamp,       [36, 168, 122]],
]);

const FALLBACK: [number, number, number] = [0, 0, 0];

export function biomeColor(id: number): string {
  const c = BIOME_COLORS.get(id) ?? FALLBACK;
  return `rgb(${c[0]},${c[1]},${c[2]})`;
}

const BIOME_NAMES = new Map<number, string>([
  [BiomeId.ocean, 'Ocean'],
  [BiomeId.plains, 'Plains'],
  [BiomeId.desert, 'Desert'],
  [BiomeId.windswept_hills, 'Windswept Hills'],
  [BiomeId.forest, 'Forest'],
  [BiomeId.taiga, 'Taiga'],
  [BiomeId.swamp, 'Swamp'],
  [BiomeId.river, 'River'],
  [BiomeId.nether_wastes, 'Nether Wastes'],
  [BiomeId.the_end, 'The End'],
  [BiomeId.frozen_ocean, 'Frozen Ocean'],
  [BiomeId.frozen_river, 'Frozen River'],
  [BiomeId.snowy_plains, 'Snowy Plains'],
  [BiomeId.snowy_mountains, 'Snowy Mountains'],
  [BiomeId.mushroom_fields, 'Mushroom Fields'],
  [BiomeId.mushroom_field_shore, 'Mushroom Field Shore'],
  [BiomeId.beach, 'Beach'],
  [BiomeId.desert_hills, 'Desert Hills'],
  [BiomeId.wooded_hills, 'Wooded Hills'],
  [BiomeId.taiga_hills, 'Taiga Hills'],
  [BiomeId.mountain_edge, 'Mountain Edge'],
  [BiomeId.jungle, 'Jungle'],
  [BiomeId.jungle_hills, 'Jungle Hills'],
  [BiomeId.sparse_jungle, 'Sparse Jungle'],
  [BiomeId.deep_ocean, 'Deep Ocean'],
  [BiomeId.stony_shore, 'Stony Shore'],
  [BiomeId.snowy_beach, 'Snowy Beach'],
  [BiomeId.birch_forest, 'Birch Forest'],
  [BiomeId.birch_forest_hills, 'Birch Forest Hills'],
  [BiomeId.dark_forest, 'Dark Forest'],
  [BiomeId.snowy_taiga, 'Snowy Taiga'],
  [BiomeId.snowy_taiga_hills, 'Snowy Taiga Hills'],
  [BiomeId.old_growth_pine_taiga, 'Old Growth Pine Taiga'],
  [BiomeId.giant_tree_taiga_hills, 'Giant Tree Taiga Hills'],
  [BiomeId.windswept_forest, 'Windswept Forest'],
  [BiomeId.savanna, 'Savanna'],
  [BiomeId.savanna_plateau, 'Savanna Plateau'],
  [BiomeId.badlands, 'Badlands'],
  [BiomeId.wooded_badlands, 'Wooded Badlands'],
  [BiomeId.badlands_plateau, 'Badlands Plateau'],
  [BiomeId.warm_ocean, 'Warm Ocean'],
  [BiomeId.lukewarm_ocean, 'Lukewarm Ocean'],
  [BiomeId.cold_ocean, 'Cold Ocean'],
  [BiomeId.deep_warm_ocean, 'Deep Warm Ocean'],
  [BiomeId.deep_lukewarm_ocean, 'Deep Lukewarm Ocean'],
  [BiomeId.deep_cold_ocean, 'Deep Cold Ocean'],
  [BiomeId.deep_frozen_ocean, 'Deep Frozen Ocean'],
  [BiomeId.sunflower_plains, 'Sunflower Plains'],
  [BiomeId.windswept_gravelly_hills, 'Windswept Gravelly Hills'],
  [BiomeId.flower_forest, 'Flower Forest'],
  [BiomeId.ice_spikes, 'Ice Spikes'],
  [BiomeId.old_growth_birch_forest, 'Old Growth Birch Forest'],
  [BiomeId.old_growth_spruce_taiga, 'Old Growth Spruce Taiga'],
  [BiomeId.windswept_savanna, 'Windswept Savanna'],
  [BiomeId.eroded_badlands, 'Eroded Badlands'],
  [BiomeId.bamboo_jungle, 'Bamboo Jungle'],
  [BiomeId.soul_sand_valley, 'Soul Sand Valley'],
  [BiomeId.crimson_forest, 'Crimson Forest'],
  [BiomeId.warped_forest, 'Warped Forest'],
  [BiomeId.basalt_deltas, 'Basalt Deltas'],
  [BiomeId.dripstone_caves, 'Dripstone Caves'],
  [BiomeId.lush_caves, 'Lush Caves'],
  [BiomeId.deep_dark, 'Deep Dark'],
  [BiomeId.meadow, 'Meadow'],
  [BiomeId.grove, 'Grove'],
  [BiomeId.snowy_slopes, 'Snowy Slopes'],
  [BiomeId.frozen_peaks, 'Frozen Peaks'],
  [BiomeId.jagged_peaks, 'Jagged Peaks'],
  [BiomeId.stony_peaks, 'Stony Peaks'],
  [BiomeId.cherry_grove, 'Cherry Grove'],
  [BiomeId.mangrove_swamp, 'Mangrove Swamp'],
]);

export function biomeName(id: number): string {
  return BIOME_NAMES.get(id) ?? `Unknown (${id})`;
}
